apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Value.image.appName }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Value.image.appName }}
  template:
    metadata:
      labels:
        app: {{ .Value.image.appName }}
    spec:
      containers:
      - name: {{ .Value.image.appName }}
        image: "{{ .Values.image.image.name }}:{{ .Values.image.image.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Value.image.appName }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Value.image.appName }}
  ports:
  - port: 4000
    targetPort: 4000