apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: socialhub-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: socialhub.com
      http:
        paths:
          - path: /taki/*
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.taki.appName }}-service
                port:
                  number: 8080
          - path: /socket.io/*
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.taki.appName }}-service
                port:
                  number: 8080
          - path: /websocket
            pathType: Prefix
            backend:
              service:
                name: {{ .Value.goChat.appName }}-service
                port:
                 number: 8000
          - path: /api/*
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.auth.appName }}-service
                port:
                 number: 4000
          - path: /api/*
            pathType: Prefix
            backend:
              service:
                name: {{ .Value.image.appName }}-service
                port:
                 number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.reactFrontend.appName }}-service
                port:
                  number: 3000

