apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.reactFrontend.appName }}deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.reactFrontend.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.reactFrontend.appName }}
    spec:
      containers:
      - name: {{ .Values.reactFrontend.appName }}
        image: "{{ .Values.reactFrontend.image.name }}:{{ .Values.reactFrontend.image.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "2000m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.reactFrontend.appName }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.reactFrontend.appName }}
  ports:
  - port: 3000
    targetPort: 3000